create table if not exists public.challenge_catalog (
  id text primary key,
  title text not null,
  description text,
  category text not null check (category in ('attivita', 'sociale', 'pensiero', 'lettura')),
  xp_reward integer not null default 1,
  difficulty_order integer not null,
  repeatable boolean not null default false,
  progress_target integer not null default 1,
  tracking_type text not null default 'client' check (tracking_type in ('client', 'hybrid', 'server')),
  status_visibility text not null default 'always' check (status_visibility in ('always')),
  icon text not null default '🎯',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.user_challenge_progress (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  challenge_id text not null,
  current_value integer not null default 0,
  completed boolean not null default false,
  completed_at timestamptz,
  times_completed integer not null default 0,
  last_notified_at timestamptz,
  meta jsonb,
  updated_at timestamptz not null default now(),
  unique (user_id, challenge_id)
);

alter table public.user_gamification
  add column if not exists current_level_points integer not null default 0,
  add column if not exists next_level_points integer not null default 16;

create or replace function public.think_level_threshold(p_level integer)
returns integer
language plpgsql
as $$
declare
  v_rank integer;
begin
  if p_level <= 1 then
    return 0;
  end if;
  v_rank := p_level - 1;
  return round((v_rank * v_rank * 4) + (v_rank * 12));
end;
$$;

create or replace function public.think_compute_depth_level(p_points integer)
returns integer
language plpgsql
as $$
declare
  v_level integer := 1;
begin
  while public.think_level_threshold(v_level + 1) <= coalesce(p_points, 0) loop
    v_level := v_level + 1;
  end loop;
  return v_level;
end;
$$;

create or replace function public.recompute_user_gamification(p_user_id uuid)
returns void
language plpgsql
as $$
declare
  v_points integer := 0;
  v_level integer := 1;
begin
  select coalesce(sum(c.xp_reward), 0)
  into v_points
  from public.user_challenge_progress ucp
  join public.challenge_catalog c on c.id = ucp.challenge_id
  where ucp.user_id = p_user_id and ucp.completed = true;

  v_level := public.think_compute_depth_level(v_points);

  insert into public.user_gamification (
    user_id,
    think_points,
    depth_level,
    streak_days,
    last_activity_date,
    current_level_points,
    next_level_points
  )
  values (
    p_user_id,
    v_points,
    v_level,
    1,
    current_date,
    public.think_level_threshold(v_level),
    public.think_level_threshold(v_level + 1)
  )
  on conflict (user_id) do update
  set
    think_points = excluded.think_points,
    depth_level = excluded.depth_level,
    current_level_points = excluded.current_level_points,
    next_level_points = excluded.next_level_points,
    updated_at = now();
end;
$$;

create or replace function public.award_periodic_challenges()
returns void
language plpgsql
as $$
declare
  v_today uuid;
  v_week uuid;
begin
  with daily_scores as (
    select user_id, count(*) as score
    from (
      select user_id from public.chats where user_id is not null and created_at >= date_trunc('day', now())
      union all
      select user_id from public.risposte where user_id is not null and created_at >= date_trunc('day', now())
    ) e
    group by user_id
    order by score desc, user_id
    limit 1
  )
  select user_id into v_today from daily_scores;

  if v_today is not null then
    insert into public.user_challenge_progress (
      user_id, challenge_id, current_value, completed, completed_at, times_completed, last_notified_at, updated_at
    )
    values (
      v_today, 'sii_il_pensatore_piu_operoso_del_giorno', 1, true, now(), 1, now(), now()
    )
    on conflict (user_id, challenge_id) do update
    set completed = true,
        current_value = greatest(public.user_challenge_progress.current_value, 1),
        completed_at = coalesce(public.user_challenge_progress.completed_at, now()),
        times_completed = greatest(public.user_challenge_progress.times_completed, 1),
        updated_at = now();
    perform public.recompute_user_gamification(v_today);
  end if;

  with weekly_scores as (
    select user_id, count(*) as score
    from (
      select user_id from public.chats
      where user_id is not null
        and created_at >= date_trunc('week', now() at time zone 'utc')::timestamptz
      union all
      select user_id from public.risposte
      where user_id is not null
        and created_at >= date_trunc('week', now() at time zone 'utc')::timestamptz
    ) e
    group by user_id
    order by score desc, user_id
    limit 1
  )
  select user_id into v_week from weekly_scores;

  if v_week is not null then
    insert into public.user_challenge_progress (
      user_id, challenge_id, current_value, completed, completed_at, times_completed, last_notified_at, updated_at
    )
    values (
      v_week, 'sii_il_pensatore_piu_attivo_della_settimana', 1, true, now(), 1, now(), now()
    )
    on conflict (user_id, challenge_id) do update
    set completed = true,
        current_value = greatest(public.user_challenge_progress.current_value, 1),
        completed_at = coalesce(public.user_challenge_progress.completed_at, now()),
        times_completed = greatest(public.user_challenge_progress.times_completed, 1),
        updated_at = now();
    perform public.recompute_user_gamification(v_week);
  end if;
end;
$$;

insert into public.challenge_catalog (
  id, title, description, category, xp_reward, difficulty_order, repeatable, progress_target, tracking_type, status_visibility, icon
)
values
  ('scrivi_un_messaggio', 'Scrivi un messaggio', 'Pubblica il tuo primo pensiero sul globo.', 'attivita', 1, 1, false, 1, 'client', 'always', '✍️'),
  ('rispondi_a_un_messaggio_altrui', 'Rispondi a un messaggio altrui', 'Aggiungi profondita rispondendo a un altro pensiero.', 'sociale', 1, 2, false, 1, 'client', 'always', '💬'),
  ('espandi_gli_orizzonti_inizia_una_nuova_conversazione', 'Espandi gli orizzonti', 'Inizia una nuova conversazione con un pensiero originale.', 'pensiero', 1, 3, false, 1, 'client', 'always', '🧭'),
  ('leggi_la_tua_prima_thinknews', 'Leggi la tua prima ThinkNews', 'Completa la lettura qualificata del tuo primo articolo.', 'lettura', 1, 4, false, 1, 'hybrid', 'always', '📰'),
  ('leggi_una_question', 'Leggi una Question', 'Apri una Question dalla sezione Tendenze e soffermati qualche secondo.', 'lettura', 1, 5, false, 1, 'client', 'always', '🔥'),
  ('scrivi_la_tua_opinione_sulla_thinknews_piu_discussa', 'Scrivi la tua opinione sulla ThinkNews piu discussa', 'Partecipa alla discussione news piu viva del momento.', 'pensiero', 1, 6, false, 1, 'client', 'always', '🗞️'),
  ('scrivi_la_tua_opinione_sulla_question_che_ti_interessa_di_piu', 'Scrivi la tua opinione sulla Question che ti interessa di piu', 'Rispondi a una Question dalla sezione Tendenze.', 'pensiero', 1, 7, false, 1, 'client', 'always', '🧠'),
  ('fai_crescere_il_tuo_pensiero_come_un_albero', 'Fai crescere il tuo pensiero come un albero', 'Porta un tuo pensiero fino allo stato di albero.', 'attivita', 2, 8, false, 1, 'client', 'always', '🌳'),
  ('spazia_partecipa_a_10_conversazioni_diverse', 'Spazia: partecipa a 10 conversazioni diverse', 'Interagisci con 10 conversazioni diverse.', 'sociale', 2, 9, false, 10, 'client', 'always', '🌍'),
  ('sii_il_pensatore_piu_operoso_del_giorno', 'Sii il pensatore piu operoso del giorno', 'Chiudi la giornata in testa alla classifica attivita.', 'attivita', 2, 10, false, 1, 'server', 'always', '☀️'),
  ('tieniti_informato_leggi_10_articoli_diversi_nel_blog', 'Tieniti informato: leggi 10 articoli diversi nel Blog', 'Completa 10 letture qualificate di articoli differenti.', 'lettura', 2, 11, false, 10, 'hybrid', 'always', '📚'),
  ('sii_il_pensatore_piu_attivo_della_settimana', 'Sii il pensatore piu attivo della settimana', 'Chiudi la settimana in testa alla classifica attivita.', 'attivita', 2, 12, false, 1, 'server', 'always', '🏁'),
  ('coinvolgi_10_pensatori_diversi_nella_tua_chat', 'Coinvolgi 10 pensatori diversi nella tua chat', 'Raccogli 10 partecipanti diversi nei pensieri creati da te.', 'sociale', 3, 13, false, 10, 'hybrid', 'always', '👥'),
  ('completa_10_sfide_diverse', 'Completa 10 sfide diverse', 'Sblocca 10 sfide differenti almeno una volta.', 'attivita', 3, 14, false, 10, 'client', 'always', '🏆'),
  ('prendi_in_mano_il_tempo_politico_instaurA_o_alimenta_10_conversazioni_sulle_thinknews_che_hai_letto', 'Prendi in mano il tempo politico', 'Installa o alimenta 10 conversazioni sulle ThinkNews che hai letto.', 'pensiero', 3, 15, false, 10, 'hybrid', 'always', '🗳️')
on conflict (id) do update
set
  title = excluded.title,
  description = excluded.description,
  category = excluded.category,
  xp_reward = excluded.xp_reward,
  difficulty_order = excluded.difficulty_order,
  repeatable = excluded.repeatable,
  progress_target = excluded.progress_target,
  tracking_type = excluded.tracking_type,
  status_visibility = excluded.status_visibility,
  icon = excluded.icon,
  updated_at = now();
